In [4]:
import numpy as np
np.random.seed(1)

from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten, Input
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder


Using TensorFlow backend.
/usr/local/src/conda3_runtime/home/envs/DSX-Python35-Spark/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# define documents
docs = ['king is man',
'a king marrys queen',
'a queen marrys king',
'some unrelated workds'
'queen is woman']
docs

['king is man',
 'a king marrys queen',
 'a queen marrys king',
 'some unrelated workdsqueen is woman']

In [14]:
vocab_size = 50

In [15]:
oh = np.array(one_hot('king queen man woman unrelated', vocab_size)).reshape(-1,1)
oh

array([[23],
       [25],
       [22],
       [ 6],
       [34]])

In [16]:
enc = OneHotEncoder()
enc.fit(np.array(range(50)).reshape(-1,1))
oh_enc = enc.transform(oh).toarray()
oh_enc

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [17]:
encoded_docs = [one_hot(d, vocab_size) for d in docs]
encoded_docs 

[[23, 42, 22], [12, 23, 35, 25], [12, 25, 35, 23], [16, 34, 12, 42, 6]]

In [18]:
max_length = 24
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
padded_docs 

array([[23, 42, 22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [12, 23, 35, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [12, 25, 35, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0],
       [16, 34, 12, 42,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [19]:
tuples = np.empty((0, 2))
for padded_doc in padded_docs:
    length = len(padded_doc)
    for i in range(length):
        if padded_doc[i] <> 0:
            if i<length-1 & padded_doc[i+1] <> 0:
                tuples = np.append(tuples, [[padded_doc[i],padded_doc[i+1]]], axis=0) 
                if i<length-2 & padded_doc[i+2] <> 0:
                    tuples = np.append(tuples, [[padded_doc[i],padded_doc[i+2]]], axis=0) 
            if i > 0:
                tuples = np.append(tuples, [[padded_doc[i],padded_doc[i-1]]], axis=0) 
                if i > 1:
                    tuples = np.append(tuples, [[padded_doc[i],padded_doc[i-2]]], axis=0) 

    
print tuples.shape
tuples



(38, 2)


array([[23., 42.],
       [23., 22.],
       [42., 22.],
       [42., 23.],
       [22., 42.],
       [22., 23.],
       [12., 23.],
       [12., 35.],
       [23., 35.],
       [23., 25.],
       [23., 12.],
       [35., 25.],
       [35., 23.],
       [35., 12.],
       [25., 35.],
       [25., 23.],
       [12., 25.],
       [12., 35.],
       [25., 35.],
       [25., 23.],
       [25., 12.],
       [35., 23.],
       [35., 25.],
       [35., 12.],
       [23., 35.],
       [23., 25.],
       [16., 34.],
       [16., 12.],
       [34., 12.],
       [34., 42.],
       [34., 16.],
       [12., 34.],
       [12., 16.],
       [42.,  6.],
       [42., 12.],
       [42., 34.],
       [ 6., 42.],
       [ 6., 12.]])

In [20]:
onehotlabels_x = enc.transform(tuples[:,0].reshape(-1, 1)).toarray()

print  onehotlabels_x.shape
print '---'
print onehotlabels_x
print '---'
print onehotlabels_x[0]

(38, 50)
---
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
---
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [21]:
onehotlabels_y = enc.transform(tuples[:,1].reshape(-1, 1)).toarray()

print  onehotlabels_y.shape
print '---'
print onehotlabels_y
print '---'
print onehotlabels_y[0]

(38, 50)
---
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
---
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0.]


In [ ]:
model = Sequential()

input = Dense(50, input_shape=(50,), activation='relu')
model.add(input)
bottleneck = Dense(2, activation='relu')
model.add(bottleneck)
model.add(Dense(50, activation='softmax'))
# compile the model
model.compile(optimizer="adam", loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

# fit the model
model.fit(onehotlabels_x, onehotlabels_y, epochs=500, verbose=1)

In [23]:
model = Sequential()
model.add(input)
model.add(bottleneck)
model.compile(optimizer=Adam(lr=0.001), loss='binary_crossentropy', metrics=['acc'])
test = model.predict(oh_enc)
print test


[[ 4.8148527  5.2279353]
 [10.759867   7.5104537]
 [ 5.034322   8.897757 ]
 [ 4.0494266 13.490577 ]
 [ 1.3467226  9.245243 ]]


In [33]:
model = Sequential()
model.add(Embedding(1000, 2, input_length=5))
model.compile('rmsprop', 'mse')

input_array = np.random.randint(1000, size=(12, 5)) # 12 documents, 5 words per document
input_array


array([[658, 953,  83, 215, 370],
       [664, 385, 977, 952, 446],
       [  5, 236, 489, 786, 190],
       [975, 863,  75, 367,  38],
       [693, 791, 151, 584, 615],
       [556, 246, 617, 900, 774],
       [895, 972,  77, 148, 818],
       [831, 950, 312, 873, 851],
       [642, 168, 390, 602, 753],
       [382, 338, 305, 612, 338],
       [198, 619, 421, 773, 513],
       [745, 687, 348, 791, 761]])

In [34]:

output_array = model.predict(input_array)
print output_array.shape
print output_array

(12, 5, 2)
[[[-0.00737526 -0.03952711]
  [ 0.03562423 -0.00054917]
  [ 0.02312161  0.01818525]
  [-0.00454276  0.04821238]
  [-0.04863647  0.02784937]]

 [[ 0.04942006  0.02649948]
  [-0.03221387  0.0339553 ]
  [-0.02424309 -0.00664258]
  [ 0.03481558 -0.0233326 ]
  [-0.02732114  0.04956144]]

 [[-0.00534445  0.04796547]
  [ 0.02785101  0.01398841]
  [ 0.02770859 -0.0203185 ]
  [ 0.01846734  0.04200679]
  [ 0.01816216 -0.03800594]]

 [[-0.00585238  0.0450164 ]
  [ 0.04364623 -0.03347833]
  [ 0.01359291 -0.03891221]
  [-0.03987021 -0.0218769 ]
  [ 0.00964461  0.04767007]]

 [[ 0.04616523  0.04316676]
  [-0.026916   -0.03370332]
  [-0.00778913  0.00687754]
  [-0.03998027 -0.01103918]
  [-0.00807313  0.02954686]]

 [[ 0.04351507 -0.04329052]
  [ 0.04884141 -0.03043994]
  [-0.01627801 -0.01220991]
  [ 0.04792753 -0.01185318]
  [ 0.02459591  0.02811902]]

 [[-0.04344755 -0.00232911]
  [ 0.02211753  0.01849543]
  [ 0.04227458 -0.04719234]
  [-0.02551355 -0.02170448]
  [ 0.01019226 -0.0179023

In [2]:
# define documents
docs = ['Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Really Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [5]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[4, 4], [48, 43], [26, 42], [36, 43], [47], [10, 6], [8, 42], [19, 48], [8, 43], [49, 30, 4, 49]]


In [6]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[ 4  4  0  0]
 [48 43  0  0]
 [26 42  0  0]
 [36 43  0  0]
 [47  0  0  0]
 [10  6  0  0]
 [ 8 42  0  0]
 [19 48  0  0]
 [ 8 43  0  0]
 [49 30  4 49]]


In [7]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [45]:
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

ValueError: Input arrays should have the same number of samples as target arrays. Found 9 input samples and 10 target samples.

In [ ]:
import numpy as np
np.hstack((model.predict(padded_docs),np.array(labels).reshape(10,1)))